### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by scoutrul** [Oleksii14/vue2-simple-carousel#3] opened 2021-10-04 18:53 UTC
Have an a problem 'document is not defined'

Tryed client-only and mounted hooks but not worked. Im using nuxt.

**Comment by Oleksii14** [comment] 2021-10-05 04:24
Can you provide an example repo please so I could investigate?

**Comment by Oleksii14** [comment] 2021-10-09 16:31
@scoutrul let me know if the issue is not actual or provide an example repo with the reproducible issue. I am closing it for now

**Closed as completed by Oleksii14** 2021-10-09 16:31 UTC
