### ISSUE TITLE
Empty slides

### ISSUE THREAD

**Issue by ilic993** [Oleksii14/vue2-simple-carousel#2] opened 2021-01-26 13:06 UTC
Hello, I am glad this package exists since it is so lightweight and I see potential in it.

I stumbled upon a bug, the amount of slides doubles.
Between every single slide another empty slide shows up so it is like:
Slide 1, blank slide, Slide 2, blank slide, Slide 3, blank slide....

I might be setting up wrong but there is not too much room for mistakes.

**Comment by Oleksii14** [comment] 2021-01-26 13:08
@ilic993 thanks for the feedback!
Can you please provide an example of your code?

**Comment by ilic993** [comment] 2021-01-26 13:11
It is a very basic setup:

```
<template>
    <SimpleCarousel :items-per-view="1" ref="carousel">
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
        <div>5</div>
        <div>6</div>
    </SimpleCarousel>
</template>
 
<script>
import SimpleCarousel from "vue2-simple-carousel";

export default {
    components: {
        SimpleCarousel
    }
}
</script> 
```

With this setup debugging shows: 
`itemsPerPage: Array[11]`
`itemsCount: 11`
`pages: 11`

**Comment by Oleksii14** [comment] 2021-01-26 14:35
@ilic993  can you please provide a version of the carousel you have installed?

**Comment by ilic993** [comment] 2021-01-26 17:29
@Oleksii14 Sorry I removed the dependencies so I can't tell right now. But it should be latest since I didn't use any of these before it should have been a clean install.

**Comment by Oleksii14** [comment] 2021-01-27 05:36
@ilic993 Sorry, but I am closing this issue since you didn't provide a minimal reproduction so I cannot fix the potential problem.
Please check you use the latest version of the package.

`npm install vue2-simple-carousel@latest --save`

Also, I created the same markup [here](https://codesandbox.io/s/priceless-brook-mht37) and it works well. Thank you

**Closed as completed** 2021-01-27 05:36 UTC
Labels: question
